version: 2
jobs:
  build:
    machine:
      image: windows-server-2019-vs2019:stable
      
    resource_class: windows.medium
    shell: C:\Program Files\Git\usr\bin\bash.exe
    environment:
      MAVEN_OPTS: -Xmx3200m
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0_181

    steps:
      - checkout
      - run: 
          name: "Build"
          command: mvn --batch-mode --update-snapshots verify
      - store_artifacts:
          path: D:\Study\Git\UnitTestCalculator
          destination: BuiltFile
  
  # test:
  #   machine:
  #     image: windows-server-2019-vs2019:stable
      
  #   resource_class: windows.medium
  #   steps:
  #     - checkout
  #     - run:
  #         name: Save test results
  #         command: |
  #           mkdir -p ~/test-results/junit/
  #           find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
  #         when: always

  #     - store_test_results:
  #         path: D:\Study\Git\UnitTestCalculator\dist


workflows:
  version: 2
  workflow:
    jobs:
      - build
      # - test:
      #     requires:
      #       - build