version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:9-jdk-sid-node-browsers
    steps:
    - checkout
    - restore_cache:
        keys:
        - gradle-{{ checksum "build.gradle" }}
    - run: gradle assemble
    - run: gradle run
    - run: gradle test
    - save_cache:
        paths:
        - ~/.gradle
        key: gradle-{{ checksum "build.gradle" }}
    - store_artifacts:
        path: build/distributions
        destination: distributions
    - store_artifacts:
        path: build/libs
        destination: libs
  
  # test:
  #   machine:
  #     image: windows-server-2019-vs2019:stable
      
  #   resource_class: windows.medium
  #   steps:
  #     - checkout
  #     - run:
  #         name: Save test results
  #         command: |
  #           mkdir -p ~/test-results/junit/
  #           find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
  #         when: always

  #     - store_test_results:
  #         path: D:\Study\Git\UnitTestCalculator\dist


workflows:
  version: 2
  workflow:
    jobs:
      - build
      # - test:
      #     requires:
      #       - build