version: 2
jobs:
  # build:
  #   docker:
  #   - image: cimg/openjdk:8.0.252-browsers
  #   steps:
  #   - checkout
  #   - restore_cache:
  #       keys:
  #       - xml-{{ checksum "build.xml" }}
  #   # - run: xml assemble
  #   - run: xml run
  #   - run: xml test
  #   - save_cache:
  #       paths:
  #       - ~/.xml
  #       key: xml-{{ checksum "build.xml" }}
  #   - store_artifacts:
  #       path: build/distributions
  #       destination: distributions
  #   - store_artifacts:
  #       path: build/libs
  #       destination: libs
  build:
    docker:
      - image: circleci/java:8-jdk
    steps:
      - checkout
      - run:
          name: Instll JDK
          command: |
            sudo apt-get update && sudo apt-get install openjdk-11-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-11-openjdk-amd64/bin/javac
            java -version
      - run:
          name: T1
          command: |
            ant -f builds/build.xml deploy:
  # test:
  #   machine:
  #     image: windows-server-2019-vs2019:stable
      
  #   resource_class: windows.medium
  #   steps:
  #     - checkout
  #     - run:
  #         name: Save test results
  #         command: |
  #           mkdir -p ~/test-results/junit/
  #           find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
  #         when: always

  #     - store_test_results:
  #         path: D:\Study\Git\UnitTestCalculator\dist


workflows:
  version: 2
  workflow:
    jobs:
      - build
      # - test:
      #     requires:
      #       - build