version: 2
jobs:
  # Job to Build Maven application
  maven-build:   
    # specify the version you desire here
    docker:
      - image: maven
      
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          key: demo-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - run: mvn package
  
  # test:
  #   machine:
  #     image: windows-server-2019-vs2019:stable
      
  #   resource_class: windows.medium
  #   steps:
  #     - checkout
  #     - run:
  #         name: Save test results
  #         command: |
  #           mkdir -p ~/test-results/junit/
  #           find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
  #         when: always

  #     - store_test_results:
  #         path: D:\Study\Git\UnitTestCalculator\dist


workflows:
  version: 2
  workflow:
    jobs:
      - maven-build
      # - test:
      #     requires:
      #       - build